### ISSUE TITLE
Slides are too small in presenter mode

### ISSUE THREAD

**Issue by bgmort** [gnab/remark#111]
In presenter mode, the slides are smaller than they could be, making them harder to read than necessary.  There's a lot of unused horizontal space.  Could I suggest rearranging the panes a little?  As an example, I'm adding this to my slideshow, giving the left side of the page to the current slide, and splitting the right side between the notes and the preview pane.  At most aspect ratios, the current slide is nearly full-sized, and the preview slide is still bigger than it is in the current layout.  My example only contains the necessary styles for it to work in webkit.

``` css
      .remark-container.remark-presenter-mode .remark-slides-area {
        width: 60%;
        height: 100%;
        top: 0;
        left: 0.5%;
      }
      .remark-container.remark-presenter-mode .remark-preview-area {
        width: 40%;
        height: 40%;
        top: 33%;
        left: 61%;
        -webkit-transform: scale(0.66);
        -webkit-transform-origin: top left;
      }
      .remark-container.remark-presenter-mode .remark-notes-area {
        left: 61%;
        top: 0%;
      }
```
