### ISSUE TITLE
Inline styles added to background image set in CSS in FF Dev edition

### ISSUE THREAD

**Issue by mandiwise** [gnab/remark#240]
I have a background image that I want to appear in the bottom left corner of every slide (it's a company logo) so I set it in my CSS:

```css
.remark-slide-content:not(.inverse) {
   background: #fff url('../public/img/red-logo.svg') no-repeat 20px bottom;
   background-size: 150px 75px;
}
```

This works great in most browsers, but in Firefox Developer Edition there's some JS ([here, I believe](https://github.com/gnab/remark/blob/8cd8b6edf83fd89277085b035564010af7ee46e7/src/remark/views/slideView.js#L83)) that overrides the position and size that I set in my CSS by adding inline styles to the element. The inline styles set the background image to its original size and position it in the middle of the slide.

Not sure why this is occurring in only FF Dev?
