### ISSUE TITLE
Class left

### ISSUE THREAD

**Issue by lionel-m** [gnab/remark#28]
Hi,

There is an error with the class `left` :

``` CSS
#slideshow .slide > .left {
    text-align: center;
}
```

Must be :

``` CSS
#slideshow .slide > .left {
    text-align: left;
}
```
