### ISSUE TITLE
Block quotes not working

### ISSUE THREAD

**Issue by fladd** [gnab/remark#305]
According to [the official Markdown page](https://daringfireball.net/projects/markdown/), block quotes should work like this:

```
> This is a block quote
```

However, this has no effect in remark.

Am I doing something wrong?

**Comment by des4maisons** [comment]
@fladd I ran into the same thing.

The markup correctly generates `<blockquote>` HTML elements, but these are not styled.

I added this CSS to my project, which made it look similar to how I wanted:

```css
blockquote {
  border-left: 0.3em solid rgba(0,0,0,0.5);
  padding: 0 15px;
  font-style: italic;
}
```

Maybe there should be some default styling for block quotes?
