### ISSUE TITLE
Code syntax highlighting: multiline comments

### ISSUE THREAD

**Issue by siddharth-krishna** [gnab/remark#324]
The syntax highlighting for code (specifically java code) does not handle multiline comments correctly. Only the first line is treated as a comment. For example:

```
<!DOCTYPE html>
<html>
    <head>
	<title>Title</title>
	<meta charset="utf-8">
    </head>
    <body>
	<textarea id="source">

# Data Structure Primitives

## Arrays


      int[] array = {1, 3, 5, 2, 6, 9};

      /*
       * Index: 0 1 2 3 4 5
       * Value: 1 3 5 2 6 9
       */

	</textarea>
	<script src="https://gnab.github.io/remark/downloads/remark-latest.min.js">
	</script>
	<script>
	 var slideshow = remark.create({
	     ratio: "4:3",
	     highlightLanguage: "java",
	     highlightStyle: "github"});
	</script>
    </body>
</html>
```

Produces non-comment like styling for the lines beginning Index and Value. This is probably a bug in whatever is used to do code syntax highlighting but I wasn't sure where to file this issue.

**Comment by johnpaxton** [comment]
Still a problem nearly two years later with, for instance, CSS highlighting:

    ---
    ## Comments
    
    CSS comments are multi-line, starting with `/*` and ending with `*/`
    
    ```css
    /* This should apply only to divs */
    div {
      background-color: red;
      /* We turned this off
      color: blue
      */
    }
    ```
    

The code in the block `/* We turned this off` should appear this way:

```css
/* This should apply only to divs */
div {
  background-color: red;
  /* We turned this off
  color: blue
  */
}
```

But in fact, only the line `/* We turned this off` is gray and italicized.
