### ISSUE TITLE
Make images fill slide without using background-image

### ISSUE THREAD

**Issue by williamsmj** [gnab/remark#331]
Is it possible to scale an image to the largest size such that both its width and its height can fit inside the slide?

Right now I am defining a css class like below for every slide I want to do this in, which is the kind of thing I was hoping to avoid by using markdown!

``` css
.foo {
    background-image: url(foo.jpg);
    background-size: contain;
}
```
