### ISSUE TITLE
Is it possible to change font color for a whole single slide?

### ISSUE THREAD

**Issue by idd79** [gnab/remark#370]
Hi and thanks for a great and simple framework. I managed to changed the background-color for a single slide (say to black) but then I haven't been able to change the font color (to say white). Is this possible at all?

Sorry if this is more related to CSS as to remark, but my knowledge of CSS is minimum. Thanks in advance!

**Comment by williamsmj** [comment]
Add this to your CSS
```css
blackslide {
    background-color: black;
    color: white !important;
}
```
and then `class: blackslide` at the start of the slide markdown.
