### ISSUE TITLE
how to remove top and bottom slide box?

### ISSUE THREAD

**Issue by dcsan** [gnab/remark#376]
I'd like to remove the top and bottom slide frame areas and stretch the whole slide, so this looks OK on a portrait mobile phone.

I don't see where the base CSS for this project is included?

currently I get this:

![image](https://cloud.githubusercontent.com/assets/514002/19408385/416a6b48-92ee-11e6-9d42-03d6775eeead.png)

**Comment by dcsan** [comment]
OK! I found the 

      var slideshow = remark.create({ ratio: "9:16" });

but this now creates a "tall only" slide.
is there anyway to remove the slide frame and just blend into the background?

![image](https://cloud.githubusercontent.com/assets/514002/19408444/9f7db374-92ef-11e6-8880-93d11b31055b.png)

I tried looking into the CSS and trying to override it but still can't see where the original css is included. is it somehow inlined via javascript?

**Comment by gnab** [comment]
You can add some extra CSS to your HTML document that will remote the shadow of the slides (removing the frame) and to set the background color for the area surrounding the slideshow:

```css
.remark-slide-scaler {
  box-shadow: none; /* remove slide frame */
}
.remark-slide-container {
  background: white; /* match slide container color with slides */
}
```

Please see [this demo](https://jsfiddle.net/wetvdrud/).

**Comment by dcsan** [comment]
thanks for that, i found those things. some questions remain

- where is the CSS included? I don't link to an external css from my demo, is it somehow built into the JS?

- is there a way to clear/none the background color in the container? then it would just match the html page background.. ?  setting to `none` didn't seem to work. maybe i have to use a transparent but that would have performance impact...

**Comment by gnab** [comment]
If you mean the default CSS, that is bundled into the remark.min.js file.

You can add a couple more CSS rules to remove the background color for the page background anad the slide itself as well:

```css
.remark-slide-scaler {
  box-shadow: none; /* remove slide frame */
}
.remark-container {
  background: none;
}
.remark-slide-container {
  background: none; /* match slide container color with slides */
}
.remark-slide-content {
  background: none;
}
```
