### ISSUE TITLE
Color of slide number affected by background-image

### ISSUE THREAD

**Issue by pat-s** [gnab/remark#405]
When using a background-image within a slide, the color of the slide number is somehow affected. Here is an example using green text color on white background:

![screenshot at jan 09 17-56-43](https://cloud.githubusercontent.com/assets/8430564/21890203/e18233ee-d8cc-11e6-8296-bbdf7fbdabad.png)

White becomes somewhat greyish and all other colours also become darker. 

```css
.remark-slide-number {
  color: green;
  background-color: white;
}
```

**Comment by tripu** [comment]
@pat-s, can you point us at a specific (complete) example?

**Comment by pat-s** [comment]
@tripu I am using [this implementation](https://github.com/yihui/xaringan) of `remark.js`. 

Using a custom css file, I can modify `remark.js` classes. Since the `xaringan` implementation is not pure `remark.js` but uses R in the background, I can only talk about the css class modifications and not provide a complete example (as it would not be executable by you).

As mentioned above, I modified the `.remark-slide-number` class. Furthermore I use a `layout` to apply the background image:

```css
layout: true

background-image: url(img/FSU/4-3/layout_4-3.png)
background-size: cover

```

This background image contains a blue bar as footer. When drawing both the slide number and the `background-image`, the weird colouring appears. 

Here is the complete modification of `.remark-slide-number`:

```css
.remark-slide-number {
  color: green;
  background-color: white;
  margin-bottom: -11.6px;
  margin-right: 20px;
  border-radius: 0px;
  padding: 1.6px;
}
```
