### ISSUE TITLE
Slide class should override global class

### ISSUE THREAD

**Issue by georgjaehnig** [gnab/remark#503]
Hi, using this code

    class: center
    layout: true
    ---
    # Standard slide
    ---
    class: left
    # Left aligned slide

I'd expect `Left aligned slide` to be left-aligned. However, it is centered. Is this a bug or is there a reason for it?

**Comment by mschilli87** [comment]
@georgjaehnig: try

```yaml
class: center
layout: true
---
# Standard slide
---
class: left
layout: false
# Left aligned slide
```

Without de-activating `layout` you effectively set `class` twice for the slide.

I agree however that intuitively I would expect the `left` setting to have override the `center`.
