### ISSUE TITLE
Separate HTML/MD and have header and footer

### ISSUE THREAD

**Issue by drorata** [gnab/remark#504]
It is my first attempt with `remark`. How can I enjoy both footers and headers and separation between HTML and MD? I try to combine #30  and #229.

From #229 I have the following:

```css
/*  slides.css */
/* Header/Footer stuff */
div.my-header {
    background-color: #F77A00;
    background: -webkit-gradient(linear, left top, right top, color-stop(0%,#ffb76b), color-stop(0%,#ffa73d), color-stop(0%,#ffffff), color-stop(10%,#ffffff), color-stop(25%,#F77A00), color-stop(100%,#F77A00));
    position: fixed;
    top: 0px;
    left: 0px;
    height: 30px;
    width: 100%;
    text-align: left;
}

div.my-footer {
    background-color: #F77A00;
    position: absolute;
    bottom: 0px;
    left: 0px;
    height: 20px;
    width: 100%;
}

div.my-footer span {
    font-size: 10pt;
    position: absolute;
    left: 15px;
    bottom: 2px;
}
```

and the example is:

```html
<!-- example.html -->
<!DOCTYPE html>
<html>
  <head>
    <title>Title</title>
    <meta charset="utf-8">
    <style>
      @import url(https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz);
      @import url(https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic);
      @import url(https://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700,400italic);

      body { font-family: 'Droid Serif'; }
      h1, h2, h3 {
        font-family: 'Yanone Kaffeesatz';
        font-weight: normal;
      }
      .remark-code, .remark-inline-code { font-family: 'Ubuntu Mono'; }
    </style>
  </head>
  <link rel="stylesheet" type="text/css" href="slides.css"/>
  <body>
    <textarea id="source">

layout: true
<div class="my-header">FOO</div>
<div class="my-footer"><span>BAR</div>

---

class: center, middle

# Title

---

# Agenda

1. Introduction
2. Deep-dive
3. ...

---

# Introduction

    </textarea>
    <script src="https://remarkjs.com/downloads/remark-latest.min.js">
    </script>
    <script>
      var slideshow = remark.create();
    </script>
  </body>
</html>
```

This works as expected and I get the desired header and footer.

However, I want to separate the HTML and the MD content (as per #30). Therefore, instead of `example.html` I have `slides.html`:

```
<!DOCTYPE html>
<html>
  <head>
    <title>Title</title>
    <meta charset="utf-8">
    <style>
      @import url(https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz);
      @import url(https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic);
      @import url(https://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700,400italic);

      body { font-family: 'Droid Serif'; }
      h1, h2, h3 {
        font-family: 'Yanone Kaffeesatz';
        font-weight: normal;
      }
      .remark-code, .remark-inline-code { font-family: 'Ubuntu Mono'; }
    </style>
  </head>
  <link rel="stylesheet" type="text/css" href="my-remark.css"/>
  <body>
    <script src="https://remarkjs.com/downloads/remark-latest.min.js">
    </script>
    <script>
      var slideshow = remark.create({
        sourceUrl: 'slides.md'
    });
    </script>
  </body>
</html>
```

and `slides.md`:

```md
layout: true
<div class="my-header">FOO</div>
<div class="my-footer"><span>BAR</span></div>

---

class: center, middle

# My slides

---

# Agenda

1. Introduction
2. Deep-dive
3. ...

---

# Introduction

Hello World!
```

However, when I open `slides.html` from a simple/local HTTP server, I cannot see the header and footer rendered properly. Both `FOO` and `BAR` are at the top of each slide (except the title where they are centered above the title).
