### ISSUE TITLE
Progress bar instead of slide numbers

### ISSUE THREAD

**Issue by royfrancis** [gnab/remark#506]
Is it possible to add a progress bar instead of slide numbers?

For example, this progress bar at the bottom from reveal.js.

![screenshot 2018-02-05 15 36 20](https://user-images.githubusercontent.com/5083500/35816040-2d7c282c-0a9a-11e8-96f3-78d748fef55d.png)

**Comment by saul** [comment]
This is quite simple to emulate.

In your CSS, add:

```css
    .remark-slide-number {
      position: inherit;
    }

    .remark-slide-number .progress-bar-container {
      position: absolute;
      bottom: 0;
      height: 2px;
      display: block;
      left: 0;
      right: 0;
    }

    .remark-slide-number .progress-bar {
      height: 100%;
      background-color: red;
    }
```

Then in your remark options, use this `slideNumberFormat`:

```js
    var slideshow = remark.create({
      slideNumberFormat: (current, total) => `
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: ${current/total*100}%">
          </div>
        </div>
      `
    });
```

Hope that helps
