### ISSUE TITLE
How to highlight text?

### ISSUE THREAD

**Issue by nashid** [gnab/remark#626]
I am trying to highlight a segment of text. As an example:

``` dark
BugSwarm: mining and continuously growing a dataset of reproducible failures and fixes
Tomassi  et al.
ICSE 2019
```
However, remark is bolding out tokens like *and*, *of*. I presume somehow it is considering those as javascript token.

Is there a way just to create a textbox with some highlighting.

**Comment by dvberkel** [comment]
The way I would highlight a block of text is to make it a quote in markdown.

```
> BugSwarm: mining and ...
```

This will become a `blockquote` in HTML, which can be styled with CSS. For example

```css
blockquote {
    border-left-style: solid;
    border-left-width: 5px;
    border-left-color: gray;
    background-color: #F2F3F4;
    padding-left: 2em;
    padding-right: 2em;
}
```
